In [2]:
import polars as pl
import sklearn as skl

In [ ]:
accounts = pl.read_csv("../Data/accounts.csv")
streams = pl.read_csv("../Data/streams.csv")

In [8]:
accounts.head()

shape: (5, 3)
┌────────────────┬───────┬─────────┐
│ account_number ┆ price ┆ churned │
│ ---            ┆ ---   ┆ ---     │
│ i64            ┆ f64   ┆ i64     │
╞════════════════╪═══════╪═════════╡
│ 650            ┆ 30.56 ┆ 1       │
│ 573            ┆ 12.04 ┆ 0       │
│ 575            ┆ 32.05 ┆ 0       │
│ 943            ┆ 30.56 ┆ 1       │
│ 924            ┆ 35.19 ┆ 0       │
└────────────────┴───────┴─────────┘

In [9]:
streams.head()

shape: (5, 4)
┌────────────────┬─────────────────┬───────────────┬────────────────────┐
│ account_number ┆ start_timestamp ┆ end_timestamp ┆ mos_score          │
│ ---            ┆ ---             ┆ ---           ┆ ---                │
│ i64            ┆ str             ┆ i64           ┆ str                │
╞════════════════╪═════════════════╪═══════════════╪════════════════════╡
│ 978            ┆ 1526775423142   ┆ 1526775485544 ┆ 4.531914893617022  │
│ 599            ┆ 1526718568735   ┆ 1526719368844 ┆ 4.595744680851064  │
│ 939            ┆ 1526768671819   ┆ 1526768981833 ┆ 4.0638297872340425 │
│ 939            ┆ 1526772855013   ┆ 1526774360750 ┆ 4.468085106382979  │
│ 749            ┆ 1526738340947   ┆ 1526740366937 ┆ 4.595744680851064  │
└────────────────┴─────────────────┴───────────────┴────────────────────┘